### PR TITLE
Ruby completions via IRB completion library

### PR DESCRIPTION
**Pull request by byteit101**
Easy enough given IRB is already in there. No type information is present like Python, but this at least brings it up to parity with a basic IRB session.

I also added `ghidra` as a easy way to reference classes using java-style package names, as `org`, `com`, `java`, `javax`, and [javafx](https://github.com/jruby/jruby/commit/1406464b35cdf7c70cb949ddca80ca0d18ec3658) do today in stock JRuby.
 
Before: `Java::GhidraAppPluginCoreConsole::CodeCompletion`
After: `ghidra.app.plugin.core.console.CodeCompletion`

### CODE REVIEW

**Comment by byteit101** [comment]
Hold on to this for a moment, I need to add some error handling due to IRB bugs that I helpfully found nearly a year ago: https://github.com/ruby/irb/issues/295

**Comment by goatshriek** [comment]
No problem, thanks for putting this together! I'll hold off on a review and CI run until you're ready to go.

**Comment by byteit101** [comment]
Ok, working well with new changes. I'm also working on making the methods top level like python, but am running into some weird issues: https://github.com/byteit101/ruby-dragon/tree/top-level-ruby I'll open a separate PR when that's fixed up a bit

**Comment by goatshriek** [comment]
Thanks again for putting this together! I suspect tab completion will be a huge quality of life improvement for folks (including myself). If you'd like a personal shoutout on Twitter please feel free to send me your handle, or I can just use the `@jruby` group one?

**Comment by byteit101** [comment]
As a tab completion addict: I totally agree. Note that due to the linked bugs in IRB/JRuby you can't do more that one dot in most cases I think?

I don't have a personal twitter, but I know headius always loves it when he hears of projects using JRuby, so please do tag `@jruby`

**Pull request merged**
